# Generated by Django 5.2.3 on 2025-06-12 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField()),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='aranceles.capitulo')),
            ],
        ),
        migrations.AddField(
            model_name='capitulo',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='aranceles.seccion'),
        ),
        migrations.CreateModel(
            name='Subpartida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=13, unique=True)),
                ('descripcion', models.TextField()),
                ('ga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ice_iehd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('despacho_en_frontera', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_de_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('entidad_que_emite', models.CharField(blank=True, max_length=255, null=True)),
                ('disposicion_legal', models.CharField(blank=True, max_length=255, null=True)),
                ('can_ace_36_47_ven', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ace_22_chile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ace_22_prot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ace_66_mexico', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpartidas', to='aranceles.partida')),
            ],
        ),
    ]
