# Generated by Django 5.2.3 on 2025-11-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranceles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pendiente', max_length=50)),
                ('filas_agregadas', models.IntegerField(default=0)),
                ('filas_modificadas', models.IntegerField(default=0)),
                ('filas_eliminadas', models.IntegerField(default=0)),
                ('detalles', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='subpartida',
            name='es_titulo_intermedio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='orden',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
