# Generated by Django 5.2.3 on 2025-11-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranceles', '0002_logactualizacion_subpartida_es_titulo_intermedio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_cambio', models.CharField(choices=[('crear', 'Creación'), ('actualizar', 'Actualización'), ('eliminar', 'Eliminación')], max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('objeto_id', models.IntegerField()),
                ('usuario', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField()),
                ('cambios_detalles', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Registro de Cambio',
                'verbose_name_plural': 'Registros de Cambios',
                'ordering': ['-fecha'],
            },
        ),
    ]
