# Generated by Django 5.2.3 on 2025-11-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aranceles', '0003_registrocambio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subpartida',
            options={'ordering': ('codigo',)},
        ),
    ]
