# Generated by Django 5.2.3 on 2025-06-17 23:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_searchlog_timestamp_alter_searchlog_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Registro de búsqueda', 'verbose_name_plural': 'Registros de búsquedas'},
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='term',
            field=models.CharField(max_length=255, verbose_name='Término buscado'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
